coverage:
  status:
    patch:
      default:
        # basic
        target: auto
        threshold: 0%
    project:
      default:
        target: auto
        # adjust accordingly based on how flaky your tests are
        # this allows a 10% drop from the previous base commit coverage
        threshold: 10%